class Lore(Scene):
    def construct(self):
        text1 = Text("Visualizing WashU Shuttles",font_size=65)
        text7 = Text("Travis Kuo and Jeslyn Gao", font_size=25)
        text1.shift(UP)
        self.play(Write(text1))
        self.play(Write(text7))
        self.wait(2)
        self.remove(text1,text7)

        text2 = Text("We wanted to create this project so")
        text3 = Text("that new WashU students could more")
        text4 = Text("easily navigate the shuttle system" )
        text5 = Text("and understand the location of the")
        text6 = Text("stops and routes of each shuttles.")
 
        group = VGroup(text2, text3, text4, text5, text6).arrange(DOWN,buff = 0.5)
        self.play(FadeIn(group), run_time=2)
        self.wait(4)
        self.play(FadeOut(group))

        text8 = Text("So we created a model of the campus")
        text9 = Text("with the main locations frequented")
        text10 = Text("by new students to visualize how")
        text11 = Text("to get from one location to another")
        text12 = Text("through the campus shuttle system!")
        group2 = VGroup(text8, text9, text10, text11, text12).arrange(DOWN,buff = 0.5)
        self.play(FadeIn(group2), run_time=2)
        self.wait(4)
        self.play(FadeOut(group2))

        textlol = Text("Yeah we got lost..........")
        textlol2 = Text("A lot.................")
        textlol.shift(UP)
        textlol2.shift(DOWN)
        self.play(FadeIn(textlol))
        self.wait(2)
        self.play(FadeIn(textlol2))
        self.wait(2)
        self.play(FadeOut(textlol,textlol2))
    
        text13 = Text("Here is a demonstration of our model")
        text14 = Text("showing the Campus Circulator line,")
        text15 = Text("the Delmar Loop line, and an example")
        text16 = Text("route of a student going from the")
        text17 = Text("560 Music Center to the Village:")
        group3 = VGroup(text13, text14, text15, text16, text17).arrange(DOWN,buff = 0.5)
        self.play(FadeIn(group3), run_time=2)
        self.wait(4)
        self.play(FadeOut(group3))
